<?php if($block->getConfigValue('general/enable') == true): ?>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getConfigValue('map/api_val'); ?>&callback=initMap"></script>
    <script>
        function initMap() {
            var point = {lat: <?php echo $block->getConfigValue('map/lat_val'); ?>, lng: <?php echo $block->getConfigValue('map/long_val'); ?>};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 16,
                center: point
            });
            var marker = new google.maps.Marker({
                position: point,
                map: map
            });
        }
    </script>
    <div id="map" style="width:<?php echo $block->getConfigValue('map/width_val'); ?>px;height:<?php echo $block->getConfigValue('map/height_val'); ?>;"></div>
<?php endif; ?>
